server:
  port: ${SERVER_PORT:8084}

spring:
  application:
    name: resource-service
  datasource:
    url: ${RESOURCE_DB_URL:jdbc:postgresql://localhost:5432/team_resource_mgmt}
    username: ${RESOURCE_DB_USERNAME:team_resource}
    password: ${RESOURCE_DB_PASSWORD:team_resource}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: resources
  flyway:
    enabled: true
    default-schema: resources
    schemas: resources
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

app:
  security:
    jwt:
      issuer: ${JWT_ISSUER:team-resource-auth}
      secret-base64: ${JWT_SECRET_BASE64:VEVBTV9SRVNPVVJDRV9NQU5BR0VNRU5UX0RFVl9TRUNSRVRfSFM1Nl8zMl9CWVRFUw==}
