import { SectionPanel } from '../../components/SectionPanel';
import type { ApprovalItem } from '../../types';

interface ApprovalsPanelProps {
  approvals: ApprovalItem[];
  loading: boolean;
  onReload: () => void;
  onApprove: (approvalId: string) => void;
  onReject: (approvalId: string) => void;
}

export function ApprovalsPanel({ approvals, loading, onReload, onApprove, onReject }: ApprovalsPanelProps) {
  const multiStepCount = approvals.filter((approval) => approval.totalSteps > 1).length;
  const bookingScopeCount = approvals.filter((approval) => approval.targetType === 'BOOKING').length;
  const eventScopeCount = approvals.filter((approval) => approval.targetType === 'EVENT').length;

  return (
    <div className="stack-grid">
      <SectionPanel
        eyebrow="Workflow"
        title="Approval queue overview"
        actions={<button className="secondary-button" type="button" onClick={onReload}>Reload</button>}
      >
        <div className="insight-grid three-column">
          <article className="insight-card accent-green">
            <small>Open queue</small>
            <strong>{approvals.length}</strong>
            <p>Pending approval requests currently routed to the signed-in approver context.</p>
          </article>
          <article className="insight-card accent-amber">
            <small>Booking-driven work</small>
            <strong>{bookingScopeCount}</strong>
            <p>Requests generated by booking policies that required manager or admin review before slot confirmation.</p>
          </article>
          <article className="insight-card accent-blue">
            <small>Step complexity</small>
            <strong>{multiStepCount}</strong>
            <p>Items using more than a single approval step, useful for showing richer workflow progression.</p>
          </article>
        </div>
      </SectionPanel>

      <SectionPanel
        eyebrow="Workflow"
        title="Pending approvals"
        actions={<div className="micro-stat-row"><span>Booking {bookingScopeCount}</span><span>Event {eventScopeCount}</span></div>}
      >
        <div className="card-list">
          {approvals.map((approval) => (
            <article className="list-card action-card showcase-card" key={approval.approvalId}>
              <div>
                <strong>{approval.title}</strong>
                <p>{approval.summary ?? approval.targetType}</p>
                <div className="micro-stat-row">
                  <span>{approval.targetType}</span>
                  <span>{approval.approvalType}</span>
                  <span>{approval.status}</span>
                  <span>Step {approval.currentStep}/{approval.totalSteps}</span>
                </div>
                <p>
                  requester {approval.requesterId}
                  {approval.targetOwnerId ? ` · owner ${approval.targetOwnerId}` : ''}
                  {approval.resourceId ? ` · resource ${approval.resourceId}` : ''}
                </p>
                {approval.history.length ? (
                  <div className="history-strip">
                    {approval.history.slice(0, 3).map((item) => (
                      <span key={item.decisionId}>{item.action}</span>
                    ))}
                  </div>
                ) : null}
              </div>
              <div className="showcase-rail">
                <div className="showcase-meter">
                  <label>Callback target</label>
                  <strong>{approval.targetType === 'BOOKING' ? 'booking-service' : 'event-service'}</strong>
                </div>
                <div className="showcase-meter">
                  <label>Decision history</label>
                  <strong>{approval.history.length} recorded actions</strong>
                </div>
                <button className="secondary-button" type="button" disabled={loading} onClick={() => onApprove(approval.approvalId)}>
                  Approve
                </button>
                <button className="danger-button" type="button" disabled={loading} onClick={() => onReject(approval.approvalId)}>
                  Reject
                </button>
              </div>
            </article>
          ))}
          {!approvals.length ? <p className="empty-state">No pending approvals.</p> : null}
        </div>
      </SectionPanel>

      <SectionPanel eyebrow="Engineering" title="Workflow engine characteristics">
        <div className="insight-grid">
          <article className="insight-card">
            <small>Chain of responsibility</small>
            <strong>Approval routing logic</strong>
            <p>
              Approval policy resolution can route booking and event requests through different handlers before a final approval definition is chosen.
            </p>
          </article>
          <article className="insight-card">
            <small>State protection</small>
            <strong>Pending to final transitions</strong>
            <p>
              Approval decisions are guarded by explicit status handling so terminal decisions cannot be replayed into inconsistent states.
            </p>
          </article>
          <article className="insight-card">
            <small>Outbox relay</small>
            <strong>Decision after commit</strong>
            <p>
              Workflow state changes persist before relay publication, keeping event fan-out and callback completion safer under failure.
            </p>
          </article>
          <article className="insight-card">
            <small>Callback integrity</small>
            <strong>Cross-service completion</strong>
            <p>
              Approval results flow back into booking or event services without changing the frontend contract for review actions.
            </p>
          </article>
          <article className="insight-card">
            <small>Step persistence</small>
            <strong>{multiStepCount} multi-step items</strong>
            <p>
              Even when most demo paths are simple, the data model can still show explicit step progression instead of a flat binary flag.
            </p>
          </article>
          <article className="insight-card">
            <small>Event-driven ingress</small>
            <strong>Observer-compatible queueing</strong>
            <p>
              Approval creation is compatible with booking-driven event ingress, making the workflow page a visible window into asynchronous orchestration.
            </p>
          </article>
        </div>
      </SectionPanel>
    </div>
  );
}
